/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductoRouteImport } from './routes/producto'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AmenazasRouteImport } from './routes/amenazas'
import { Route as IndexRouteImport } from './routes/index'

const ProductoRoute = ProductoRouteImport.update({
  id: '/producto',
  path: '/producto',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenazasRoute = AmenazasRouteImport.update({
  id: '/amenazas',
  path: '/amenazas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amenazas': typeof AmenazasRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/empresas': typeof EmpresasRoute
  '/producto': typeof ProductoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amenazas': typeof AmenazasRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/empresas': typeof EmpresasRoute
  '/producto': typeof ProductoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amenazas': typeof AmenazasRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/empresas': typeof EmpresasRoute
  '/producto': typeof ProductoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/amenazas' | '/auth' | '/docs' | '/empresas' | '/producto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/amenazas' | '/auth' | '/docs' | '/empresas' | '/producto'
  id:
    | '__root__'
    | '/'
    | '/amenazas'
    | '/auth'
    | '/docs'
    | '/empresas'
    | '/producto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmenazasRoute: typeof AmenazasRoute
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  EmpresasRoute: typeof EmpresasRoute
  ProductoRoute: typeof ProductoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/producto': {
      id: '/producto'
      path: '/producto'
      fullPath: '/producto'
      preLoaderRoute: typeof ProductoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenazas': {
      id: '/amenazas'
      path: '/amenazas'
      fullPath: '/amenazas'
      preLoaderRoute: typeof AmenazasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmenazasRoute: AmenazasRoute,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  EmpresasRoute: EmpresasRoute,
  ProductoRoute: ProductoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
